import { Command } from 'commander';
import pc from 'picocolors';
import { resolve, join, relative } from 'path';
import { readdirSync, statSync, readFileSync, writeFileSync } from 'fs';
import { fileExists } from '../utils/file-generator.js';

export function registerEnvCommand(program: Command) {
  program
    .command('env:check')
    .description('Valida, audita y autogenera la configuración de variables de entorno')
    .option('--entry <entry>', 'Archivo de entrada de la aplicación', 'src/main.ts')
    .option('--example', 'Generar el archivo .env.example en base a los esquemas registrados')
    .option('--audit', 'Auditar accesos inseguros directos (raw) a process.env en src/')
    .action(async (options: { entry: string; example?: boolean; audit?: boolean }) => {
      const entryPath = resolve(process.cwd(), options.entry);

      // --- MODO AUDITORÍA ESTÁTICA ---
      if (options.audit) {
        console.log(pc.cyan('🔍 Iniciando auditoría estática de process.env en src/...'));
        const srcDir = resolve(process.cwd(), 'src');

        try {
          if (!statSync(srcDir).isDirectory()) {
            console.error(pc.red('Error: El directorio src/ no existe en este proyecto.'));
            process.exit(1);
          }
        } catch {
          console.error(pc.red('Error: No se pudo acceder al directorio src/.'));
          process.exit(1);
        }

        const files = getFilesRecursively(srcDir);
        let auditFailed = false;

        for (const file of files) {
          // Ignorar archivos de pruebas
          if (
            file.endsWith('.spec.ts') ||
            file.endsWith('.test.ts') ||
            file.includes('__tests__')
          ) {
            continue;
          }

          const content = readFileSync(file, 'utf-8');
          const lines = content.split('\n');

          for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const cleanLine = line.replace(/\/\/.*$/, '').replace(/\/\*.*?\*\//g, '');

            if (cleanLine.includes('process.env')) {
              // Validar si es una línea que no está usando el wrapper de env() de kanji
              // e.g. process.env.DATABASE_URL en lugar de env('DATABASE_URL')
              const relativePath = relative(process.cwd(), file);
              console.error(
                pc.red(`❌ Acceso inseguro directo detectado en ${relativePath}:${i + 1}`),
              );
              console.error(pc.gray(`   > ${line.trim()}`));
              auditFailed = true;
            }
          }
        }

        if (auditFailed) {
          console.error(
            pc.bold(
              pc.red(
                '\n❌ Auditoría fallida: Se encontraron accesos directos a process.env. Migralos a env() de @kanjijs/common.',
              ),
            ),
          );
          process.exit(1);
        }

        console.log(
          pc.bold(
            pc.green('\n✅ Auditoría exitosa: No se encontraron accesos inseguros a process.env.'),
          ),
        );
        return;
      }

      // --- CARGA DINÁMICA DE LA APLICACIÓN PARA MODOS CHECK/EXAMPLE ---
      console.log(
        pc.cyan(`Bootstrappeando aplicación desde ${options.entry} para registrar variables...`),
      );

      if (!(await fileExists(entryPath))) {
        console.error(pc.red(`Error: Archivo de entrada no encontrado en: ${options.entry}`));
        process.exit(1);
      }

      // Prevenir inicialización de base de datos o servidores HTTP durante la carga
      process.env.KANJI_GENERATE_ONLY = 'true';

      try {
        await import(entryPath);
      } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        console.error(pc.red(`Error cargando la aplicación: ${msg}`));
        process.exit(1);
      }

      const { getRegisteredEnvs } = await import('@kanjijs/common');
      const registeredEnvs = getRegisteredEnvs();

      if (registeredEnvs.size === 0) {
        console.log(
          pc.yellow('⚠️ No se encontraron variables de entorno registradas en el runtime.'),
        );
        return;
      }

      // --- MODO GENERACIÓN DE .ENV.EXAMPLE ---
      if (options.example) {
        console.log(pc.cyan('Generating .env.example file...'));
        let exampleContent = '# Autogenerated by kanji env:check --example\n\n';

        for (const [key, schema] of registeredEnvs.entries()) {
          // Extraer descripción de Zod si existe
          if (schema.description) {
            exampleContent += `# ${schema.description}\n`;
          }

          // Extraer valor por defecto
          let defaultValue = '';
          const def = schema._def as { defaultValue?: () => unknown };
          if (def && typeof def.defaultValue === 'function') {
            try {
              defaultValue = String(def.defaultValue());
            } catch {}
          }

          exampleContent += `${key}=${defaultValue}\n\n`;
        }

        const examplePath = join(process.cwd(), '.env.example');
        writeFileSync(examplePath, exampleContent, 'utf-8');
        console.log(
          pc.bold(pc.green(`\n✅ .env.example generado exitosamente en la raíz del proyecto.`)),
        );
        return;
      }

      // --- MODO VALIDACIÓN DE VARIABLES ---
      console.log(pc.cyan('Checking environment variables...\n'));
      let validationFailed = false;

      for (const [key, schema] of registeredEnvs.entries()) {
        const value = process.env[key];
        const isOptional = schema.safeParse(undefined).success;

        if (value !== undefined) {
          const parseResult = schema.safeParse(value);
          if (parseResult.success) {
            console.log(pc.green(`  ✅ ${key}`));
          } else {
            const errorMessages = parseResult.error.issues
              .map((i: { message: string }) => i.message)
              .join(', ');
            console.error(pc.red(`  ❌ ${key}: Valor inválido (${errorMessages})`));
            validationFailed = true;
          }
        } else {
          if (isOptional) {
            console.log(pc.yellow(`  ⚠️ ${key} (opcional - ausente)`));
          } else {
            console.error(pc.red(`  ❌ ${key} (requerido - ausente)`));
            validationFailed = true;
          }
        }
      }

      if (validationFailed) {
        console.error(
          pc.bold(
            pc.red('\n❌ Validación fallida: Corrige las variables de entorno antes de continuar.'),
          ),
        );
        process.exit(1);
      }

      console.log(
        pc.bold(
          pc.green(
            '\n✅ Validación exitosa: Todas las variables de entorno están correctamente configuradas.',
          ),
        ),
      );
    });
}

function getFilesRecursively(dir: string): string[] {
  let results: string[] = [];
  const list = readdirSync(dir);
  for (const file of list) {
    const filePath = join(dir, file);
    const stat = statSync(filePath);
    if (stat && stat.isDirectory()) {
      if (file !== 'node_modules' && file !== 'dist' && file !== '.git') {
        results = results.concat(getFilesRecursively(filePath));
      }
    } else if (filePath.endsWith('.ts') || filePath.endsWith('.tsx')) {
      results.push(filePath);
    }
  }
  return results;
}
