import { ProjectOptions } from '../types.js';

export function getPackageJsonTemplate(appName: string, opts: ProjectOptions): object {
  // Use the CLI's version when available, fall back to 'latest'.
  const versionSpec = opts.version ? `^${opts.version}` : 'latest';

  const dependencies: Record<string, string> = {
    '@kanjijs/core': versionSpec,
    '@kanjijs/platform-hono': versionSpec,
    '@kanjijs/contracts': versionSpec,
    '@kanjijs/cli': versionSpec,
    hono: '^4.12.27',
    zod: '^3.0.0',
    'reflect-metadata': '^0.2.2',
  };

  const devDependencies: Record<string, string> = {
    'bun-types': '^1.3.14',
    typescript: '^6.0.3',
  };

  if (opts.db === 'postgres') {
    dependencies['@kanjijs/store'] = versionSpec;
    dependencies['drizzle-orm'] = '^0.45.2';
    dependencies['pg'] = '^8.11.3';
    devDependencies['@types/pg'] = '^8.11.2';
    devDependencies['drizzle-kit'] = '^0.30.0';
  } else if (opts.db === 'mongodb') {
    dependencies['@kanjijs/store'] = versionSpec;
    dependencies['mongodb'] = '^6.0.0';
  }

  if (opts.auth && opts.auth.length > 0) {
    dependencies['@kanjijs/auth'] = versionSpec;
  }

  if (opts.openapi) {
    dependencies['@kanjijs/openapi'] = versionSpec;
  }

  if (opts.tests) {
    devDependencies['@kanjijs/testing'] = versionSpec;
  }

  const scripts: Record<string, string> = {
    dev: 'kanji dev',
    build: 'kanji build',
    start: 'kanji start',
  };

  if (opts.db === 'postgres') {
    scripts['db:push'] = 'kanji db:push';
    scripts['db:migrate'] = 'kanji migrate';
    scripts['db:generate'] = 'kanji migrate:create';
    scripts['db:studio'] = 'kanji db:studio';
  }

  const pm = opts.pm || 'bun';

  if (opts.tests) {
    scripts['test'] = pm === 'bun' ? 'bun test' : 'vitest run';
    if (pm !== 'bun') {
      devDependencies['vitest'] = '^1.0.0';
    }
  }

  return {
    name: appName,
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts,
    dependencies,
    devDependencies,
  };
}

export function getTsConfigTemplate(): object {
  return {
    compilerOptions: {
      target: 'ESNext',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      types: ['bun-types'],
    },
    include: ['src/**/*'],
  };
}

export function getMainTsTemplate(): string {
  return `import { KanjijsAdapter } from '@kanjijs/platform-hono';
import { AppModule } from './app.module.js';

async function bootstrap() {
  const { app } = await KanjijsAdapter.create(AppModule);
  
  console.log('Server is running on http://localhost:3000 🚀');
  Bun.serve({
    fetch: app.fetch,
    port: 3000,
  });
}

bootstrap();
`;
}

export function getAppModuleTemplate(opts: ProjectOptions): string {
  const imports: string[] = [
    "import { KanjijsModule } from '@kanjijs/core';",
    "import { AppController } from './app.controller.js';",
  ];

  const moduleImports: string[] = [];

  if (opts.db === 'postgres') {
    imports.push("import { StoreModule } from '@kanjijs/store';");
    moduleImports.push(`StoreModule.forRoot({
      type: 'postgres',
      connectionString:
        process.env.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/kanji_db',
    })`);
  } else if (opts.db === 'mongodb') {
    imports.push("import { StoreModule } from '@kanjijs/store';");
    moduleImports.push(`StoreModule.forRoot({
      type: 'mongodb',
      connectionString:
        process.env.DATABASE_URL || 'mongodb://root:password@localhost:27017/kanji_db?authSource=admin',
    })`);
  }

  if (opts.auth && opts.auth.length > 0) {
    imports.push("import { AuthModule } from '@kanjijs/auth';");
    moduleImports.push(`AuthModule.forRoot({
      jwtSecret: process.env.JWT_SECRET || 'dev-secret-key-12345',
    })`);
  }

  if (opts.openapi) {
    imports.push("import { OpenApiModule } from '@kanjijs/openapi';");
    moduleImports.push(`OpenApiModule.forRoot({
      title: '${opts.appName} API',
      version: '1.0.0',
      description: 'API generated by Kanji CLI',
    })`);
  }

  const importsStr = imports.join('\n');
  const moduleImportsStr = moduleImports.length > 0 
    ? `\n  imports: [\n    ${moduleImports.join(',\n    ')}\n  ],` 
    : '';

  return `${importsStr}

@KanjijsModule({${moduleImportsStr}
  controllers: [AppController],
  providers: [],
})
export class AppModule {}
`;
}

export function getAppControllerTemplate(): string {
  return `import { Controller, Get } from '@kanjijs/platform-hono';
import { type Context } from 'hono';

@Controller('')
export class AppController {
  @Get('/')
  index(c: Context): Response {
    return c.json({ message: 'Welcome to Kanji Framework!' });
  }
}
`;
}

export function getGitIgnoreTemplate(): string {
  return `node_modules/
dist/
.env
drizzle/
.DS_Store
*.log
`;
}

export function getReadmeTemplate(appName: string, opts: ProjectOptions): string {
  const pm = opts.pm || 'bun';
  const installCmd = pm === 'bun' ? 'bun install' : `${pm} install`;

  return `# ${appName}

Generated with Kanji Framework CLI.

## Quick Start

1. Install dependencies:
   \`\`\`bash
   ${installCmd}
   \`\`\`

2. Start the development server:
   \`\`\`bash
   ${pm} run dev
   \`\`\`

## Architecture & Features
${opts.db && opts.db !== 'none' ? `- **Database:** ${opts.db === 'postgres' ? 'PostgreSQL (Drizzle ORM)' : 'MongoDB (Native adapter)'}\n` : ''}${opts.auth && opts.auth.length > 0 ? `- **Authentication:** Active providers: ${opts.auth.join(', ')}\n` : ''}${opts.openapi ? '- **OpenAPI Documentation:** Enabled via OpenApiModule\n' : ''}${opts.tests ? '- **Testing:** Integration tests enabled\n' : ''}
`;
}

export function getAppE2ETestTemplate(): string {
  return `import { describe, it, expect, beforeAll } from 'bun:test';
import { KanjijsAdapter } from '@kanjijs/platform-hono';
import { AppModule } from '../app.module.js';
import type { Hono } from 'hono';

describe('AppController (E2E)', () => {
  let app: Hono;

  beforeAll(async () => {
    const adapter = await KanjijsAdapter.create(AppModule);
    app = adapter.app;
  });

  it('GET / should return welcome message', async () => {
    const res = await app.request('/');
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.message).toBe('Welcome to Kanji Framework!');
  });
});
`;
}

export function getDbSchemaTemplate(): string {
  return `import { pgTable, uuid, varchar, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: varchar('name', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;
}

export function getDbSeedTemplate(): string {
  return `import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import { users } from './schema/index.js';

const pool = new pg.Pool({
  connectionString: process.env.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/kanji_db',
});

const db = drizzle(pool);

async function main() {
  console.log('Seeding database...');
  await db.insert(users).values([
    {
      email: 'admin@kanji.dev',
      name: 'Admin User',
    },
  ]);
  console.log('Seed completed successfully!');
  await pool.end();
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
`;
}
